version: '3'

services:
  nginx:
    container_name: ety_nginx
    image: nginx:latest
    ports:
      - "8011:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    container_name: ety_php
    build:
      context: ./docker/php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: ety_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ety_case
      MYSQL_DATABASE: ety_case
      MYSQL_USER: ety_case
      MYSQL_PASSWORD: ety_case
    ports:
      - "3311:3306"
    volumes:
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql

  redis:
    container_name: ety_redis
    image: redis:latest
    ports:
      - "6380:6379"